name: .NET
# How do we want to run our project(triggers, auto when push or pull-request, on manual?(https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

env:
  WORKING_DIRECTORY: RestaurantApp
jobs: #step by step instruction 
  ci: #name of job

    runs-on: windows-latest #type of OS you want to run your build on (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
    
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
          
    - uses: actions/checkout@v3 # source code
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}} #need to make sure it points to the correct app location
    - name: Test
      run: dotnet test --verbosity normal ${{env.WORKING_DIRECTORY}}/RestuarantAPI #need to make sure it points to the correct app location
     #need to make sure it points to the correct app location
    - name: Build and analyze
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Daniel2320_Restaurant-Reviews" /o:"danielokey12" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build ${{env.WORKING_DIRECTORY}}
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
      
      
